### PR TITLE
Added SQLDriverFactory

### PR DESCRIPTION
**Pull request by x7airworker**
The new SQLDriverFactory provides a more dynamic approach to construct sql implementations, with the ability to register custom implementations.
Usage: `new SQLDriverFactory(properties).getDriver("mysql");`
Tests are included.

### CODE REVIEW

**Comment by TimothyGillespie** [comment]
If I am seeing this correctly this still needs to be embedded into the ORM?

**Comment by x7airworker** [comment]
What do you mean? This is a pull request for the ORM.

**Comment by TimothyGillespie** [comment]
I just went through the Discord chat and I think I understand now. So the ORM Library wouldn't use this library instead this is mainly made for the Framework to decouple it? Did I understand this correctly now?

**Comment by x7airworker** [comment]
The plan is to use the new DriverFactory in the Web-Framework later, this allows us to update the ORM and add new drivers/implementations without needing to update the Web-Framework.

**Pull request merged**
